---
# Example Configuration:
#
#Wwwision:
#  ImportService:
#    presetTemplates:
#      'some:template':
#        syncOnly: false
#        source:
#          factory: 'Wwwision\ImportService\DataSource\Dbal\DbalSourceFactory'
#          options:
#            backendOptions:
#              dbname: 'some-db-name'
#            table: 'source-table'
#        target:
#          factory: 'Wwwision\ImportService\DataTarget\Dbal\DbalTargetFactory'
#          options:
#            table: 'target-table'
#            idColumn: 'slug'
#            versionColumn: 'version'
#    presets:
#      'some:preset':
#        template: 'some:template'
#        source:
#          options:
#            table: 'changed-source-table'
#          fixture:
#            file: 'resource://some/file'
#          postProcessor: 'Some\Package::processRecords'
#        mapping:
#          'slug': 'id'
#          'givenname': '${String.firstLetterToUpperCase(record.firstName)}'
#          'familyname': 'lastname'
#          'version': 'revision'
Wwwision:
  ImportService:
    presetTemplates: []
    presets: []
